#variables:
#  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg TRUSTSTORE_URL=$K8S_SECRET_TRUSTSTORE_URL --build-arg TRUSTSTORE_PATH=$K8S_SECRET_TRUSTSTORE_PATH"

#include:
#  - project: 'IT/autodevops'
#    file: '/Auto-DevOps.gitlab-ci.yml'

Unit_test:
  stage: test
  # Gradle JDK 17, version published in early 2022, before a tag update made the test fail inside Gitlab runner
  name: gradle@sha256:058e381853dd5c4d2f629445bc1c4de5f1978eac956aa57372e91463befa5820
  tags:
    - dind
  script:
    - mv src/main/resources/application.properties.dist src/main/resources/application.properties
    - gradle test --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/jacoco-report/

coverage:
  stage: test
  tags:
    - dind
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    # Change /src/main/java to /src/main/kotlin if you are using kotlin
    - python /opt/cover2cover.py build/jacoco-report/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
    - cat build/jacoco-report/index.html | grep -o 'Total[^%]*%'
  coverage: '/Total.*?([0-9]{1,3})%/'
  needs: [ "unit_test" ]
  dependencies:
    - unit_test
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
