#variables:
#  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: "--build-arg TRUSTSTORE_URL=$K8S_SECRET_TRUSTSTORE_URL --build-arg TRUSTSTORE_PATH=$K8S_SECRET_TRUSTSTORE_PATH"

#include:
#  - project: 'IT/autodevops'
#    file: '/Auto-DevOps.gitlab-ci.yml'

Unit_test:
  stage: test
  image: 8.0.1-jdk19
  tags:
    - kubernetes
  script:
    - gradle test --no-daemon
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/jacoco-report/

coverage:
  stage: test
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    # Change /src/main/java to /src/main/kotlin if you are using kotlin
    - python /opt/cover2cover.py build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
    - cat build/reports/jacoco/test/html/index.html | grep -o 'Total[^%]*%'
  needs: [ "Unit_test" ]
  artifacts:
    expire_in: 1 week
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml
  tags:
    - docker
  coverage: '/Total.*?([0-9]{1,3})%/'
  dependencies:
    - unit_test
