quarkus:
  tls:
    trust-all: true
  http:
    non-application-root-path: /
  # Configure SSL (for HTTPS + disable HTTP), only production useless for tests & local dev
    ssl-port: 8044
    ssl:
      certificate.files: ${SSL_CERTIFICATE_FILE_PATH:server.pem}
      certificate.key-files: ${SSL_CERTIFICATE_KEY_PATH:server.key}
      insecure-requests: disabled
  smallrye-health:
    liveness-path: /health-check
  micrometer:
    export:
      prometheus:
        path: /metrics

  # Configure GELF Logging
  log:
    handler:
      gelf:
        enabled: true
        include-log-message-parameters: false
        include-full-mdc: true
        host: ${GELF_LOG_HOST:logstash.infra.aws.internal}
        port: ${GELF_LOG_PORT:12201}
        level: ${GELF_LOG_LEVEL:INFO}
        additional-field:
          "app":
            value: CHANGE_APP
            type: String
          "tags":
            value: customer-platform
            type: String
          "env":
            value: ${ENVIRONMENT:dev}
            type: String
          "zone":
            value: ${ZONE:default-zone}
            type: String
          "version":
            value: ${VERSION:default-version}
            type: String
    console:
      enable: false
