quarkus:
  log:
    category:
      "io.quarkus.category":
        level: INFO
  http:
    port: 8080
  smallrye-health:
    liveness-path: /health-check
  micrometer:
    export:
      prometheus:
        path: /metrics
